// <auto-generated />
using Alpacashow.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using System;

namespace Alpacashow.Data.Migrations
{
    [DbContext(typeof(AlpacashowContext))]
    [Migration("20180307102057_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Alpacashow.Data.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BreedId");

                    b.Property<string>("Chip")
                        .IsRequired();

                    b.Property<int>("ColorId");

                    b.Property<string>("Dam")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<DateTime>("Dob");

                    b.Property<string>("FarmName");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("SexId");

                    b.Property<DateTime>("SheerDate");

                    b.Property<string>("Sire")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("AnimalId");

                    b.HasIndex("BreedId");

                    b.HasIndex("ColorId");

                    b.HasIndex("SexId");

                    b.ToTable("Animal");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Animal");
                });

            modelBuilder.Entity("Alpacashow.Data.Models.Enums.AgeClass", b =>
                {
                    b.Property<int>("AgeClassId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("AgeClassId");

                    b.ToTable("AgeClasses");
                });

            modelBuilder.Entity("Alpacashow.Data.Models.Enums.Breed", b =>
                {
                    b.Property<int>("BreedId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("BreedId");

                    b.ToTable("Breeds");
                });

            modelBuilder.Entity("Alpacashow.Data.Models.Enums.Color", b =>
                {
                    b.Property<int>("ColorId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("FleeceshowEventShowEventId");

                    b.Property<int?>("HaltershowEventShowEventId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("ColorId");

                    b.HasIndex("FleeceshowEventShowEventId");

                    b.HasIndex("HaltershowEventShowEventId");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("Alpacashow.Data.Models.Enums.Sex", b =>
                {
                    b.Property<int>("SexId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("SexId");

                    b.ToTable("Sexes");
                });

            modelBuilder.Entity("Alpacashow.Data.Models.FemaleProgeny", b =>
                {
                    b.Property<int>("FemaleProgenyId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Animal1AnimalId");

                    b.Property<int?>("Animal2AnimalId");

                    b.Property<int?>("HaltershowEventShowEventId");

                    b.HasKey("FemaleProgenyId");

                    b.HasIndex("Animal1AnimalId");

                    b.HasIndex("Animal2AnimalId");

                    b.HasIndex("HaltershowEventShowEventId");

                    b.ToTable("FemaleProgeny");
                });

            modelBuilder.Entity("Alpacashow.Data.Models.FleeceshowEvent", b =>
                {
                    b.Property<int>("ShowEventId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Archived");

                    b.Property<DateTime>("Date");

                    b.Property<int?>("FleeceshowOrderId");

                    b.Property<string>("Judge")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("ShowEventId");

                    b.HasIndex("FleeceshowOrderId");

                    b.ToTable("FleeceshowEvents");
                });

            modelBuilder.Entity("Alpacashow.Data.Models.FleeceshowOrder", b =>
                {
                    b.Property<int>("FleeceshowOrderId")
                        .ValueGeneratedOnAdd();

                    b.HasKey("FleeceshowOrderId");

                    b.ToTable("FleeceshowOrder");
                });

            modelBuilder.Entity("Alpacashow.Data.Models.HaltershowEvent", b =>
                {
                    b.Property<int>("ShowEventId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Archived");

                    b.Property<DateTime>("Date");

                    b.Property<int?>("HaltershowOrderId");

                    b.Property<string>("Judge")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("ShowEventId");

                    b.HasIndex("HaltershowOrderId");

                    b.ToTable("HaltershowEvents");
                });

            modelBuilder.Entity("Alpacashow.Data.Models.HaltershowOrder", b =>
                {
                    b.Property<int>("HaltershowOrderId")
                        .ValueGeneratedOnAdd();

                    b.HasKey("HaltershowOrderId");

                    b.ToTable("HaltershowOrder");
                });

            modelBuilder.Entity("Alpacashow.Data.Models.MaleProgeny", b =>
                {
                    b.Property<int>("MaleProgenyId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Animal1AnimalId");

                    b.Property<int?>("Animal2AnimalId");

                    b.Property<int?>("Animal3AnimalId");

                    b.Property<int?>("HaltershowEventShowEventId");

                    b.HasKey("MaleProgenyId");

                    b.HasIndex("Animal1AnimalId");

                    b.HasIndex("Animal2AnimalId");

                    b.HasIndex("Animal3AnimalId");

                    b.HasIndex("HaltershowEventShowEventId");

                    b.ToTable("MaleProgeny");
                });

            modelBuilder.Entity("Alpacashow.Data.Models.FleeceshowAnimal", b =>
                {
                    b.HasBaseType("Alpacashow.Data.Models.Animal");

                    b.Property<DateTime>("BeforeSheerDate");

                    b.Property<int?>("FleeceshowEventShowEventId");

                    b.HasIndex("FleeceshowEventShowEventId");

                    b.ToTable("FleeceshowAnimal");

                    b.HasDiscriminator().HasValue("FleeceshowAnimal");
                });

            modelBuilder.Entity("Alpacashow.Data.Models.HaltershowAnimal", b =>
                {
                    b.HasBaseType("Alpacashow.Data.Models.Animal");

                    b.Property<int?>("HaltershowEventShowEventId");

                    b.HasIndex("HaltershowEventShowEventId");

                    b.ToTable("HaltershowAnimal");

                    b.HasDiscriminator().HasValue("HaltershowAnimal");
                });

            modelBuilder.Entity("Alpacashow.Data.Models.Animal", b =>
                {
                    b.HasOne("Alpacashow.Data.Models.Enums.Breed", "Breed")
                        .WithMany()
                        .HasForeignKey("BreedId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Alpacashow.Data.Models.Enums.Color", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Alpacashow.Data.Models.Enums.Sex", "Sex")
                        .WithMany()
                        .HasForeignKey("SexId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Alpacashow.Data.Models.Enums.Color", b =>
                {
                    b.HasOne("Alpacashow.Data.Models.FleeceshowEvent")
                        .WithMany("Colors")
                        .HasForeignKey("FleeceshowEventShowEventId");

                    b.HasOne("Alpacashow.Data.Models.HaltershowEvent")
                        .WithMany("Colors")
                        .HasForeignKey("HaltershowEventShowEventId");
                });

            modelBuilder.Entity("Alpacashow.Data.Models.FemaleProgeny", b =>
                {
                    b.HasOne("Alpacashow.Data.Models.Animal", "Animal1")
                        .WithMany()
                        .HasForeignKey("Animal1AnimalId");

                    b.HasOne("Alpacashow.Data.Models.Animal", "Animal2")
                        .WithMany()
                        .HasForeignKey("Animal2AnimalId");

                    b.HasOne("Alpacashow.Data.Models.HaltershowEvent", "HaltershowEvent")
                        .WithMany("FemaleProgenys")
                        .HasForeignKey("HaltershowEventShowEventId");
                });

            modelBuilder.Entity("Alpacashow.Data.Models.FleeceshowEvent", b =>
                {
                    b.HasOne("Alpacashow.Data.Models.FleeceshowOrder", "FleeceshowOrder")
                        .WithMany()
                        .HasForeignKey("FleeceshowOrderId");
                });

            modelBuilder.Entity("Alpacashow.Data.Models.HaltershowEvent", b =>
                {
                    b.HasOne("Alpacashow.Data.Models.HaltershowOrder", "HaltershowOrder")
                        .WithMany()
                        .HasForeignKey("HaltershowOrderId");
                });

            modelBuilder.Entity("Alpacashow.Data.Models.MaleProgeny", b =>
                {
                    b.HasOne("Alpacashow.Data.Models.Animal", "Animal1")
                        .WithMany()
                        .HasForeignKey("Animal1AnimalId");

                    b.HasOne("Alpacashow.Data.Models.Animal", "Animal2")
                        .WithMany()
                        .HasForeignKey("Animal2AnimalId");

                    b.HasOne("Alpacashow.Data.Models.Animal", "Animal3")
                        .WithMany()
                        .HasForeignKey("Animal3AnimalId");

                    b.HasOne("Alpacashow.Data.Models.HaltershowEvent", "HaltershowEvent")
                        .WithMany("MaleProgenys")
                        .HasForeignKey("HaltershowEventShowEventId");
                });

            modelBuilder.Entity("Alpacashow.Data.Models.FleeceshowAnimal", b =>
                {
                    b.HasOne("Alpacashow.Data.Models.FleeceshowEvent", "FleeceshowEvent")
                        .WithMany("FleeceshowAnimals")
                        .HasForeignKey("FleeceshowEventShowEventId");
                });

            modelBuilder.Entity("Alpacashow.Data.Models.HaltershowAnimal", b =>
                {
                    b.HasOne("Alpacashow.Data.Models.HaltershowEvent", "HaltershowEvent")
                        .WithMany("HaltershowAnimals")
                        .HasForeignKey("HaltershowEventShowEventId");
                });
#pragma warning restore 612, 618
        }
    }
}
