// <auto-generated />
using Alpacashow.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Alpacashow.Migrations
{
    [DbContext(typeof(AlpacashowContext))]
    partial class AlpacashowContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Alpacashow.Models.AgeClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("SortOrder");

                    b.HasKey("Id");

                    b.ToTable("AgeClasses");
                });

            modelBuilder.Entity("Alpacashow.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("BreedId");

                    b.Property<string>("Chip")
                        .IsRequired();

                    b.Property<int?>("ColorId");

                    b.Property<string>("Dam");

                    b.Property<DateTime>("Dob");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int?>("ParticipantId");

                    b.Property<int?>("SexId");

                    b.Property<int?>("ShowEventId");

                    b.Property<string>("Sire");

                    b.HasKey("Id");

                    b.HasIndex("BreedId");

                    b.HasIndex("ColorId");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("SexId");

                    b.HasIndex("ShowEventId");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("Alpacashow.Models.Breed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("SortOrder");

                    b.HasKey("Id");

                    b.ToTable("Breeds");
                });

            modelBuilder.Entity("Alpacashow.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("SortOrder");

                    b.HasKey("Id");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("Alpacashow.Models.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FarmName")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int?>("ShowEventId");

                    b.HasKey("Id");

                    b.HasIndex("ShowEventId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("Alpacashow.Models.Sex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("SortOrder");

                    b.HasKey("Id");

                    b.ToTable("Sexes");
                });

            modelBuilder.Entity("Alpacashow.Models.ShowEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Archived");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Judge")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("ShowEvents");
                });

            modelBuilder.Entity("Alpacashow.Models.Animal", b =>
                {
                    b.HasOne("Alpacashow.Models.Breed", "Breed")
                        .WithMany()
                        .HasForeignKey("BreedId");

                    b.HasOne("Alpacashow.Models.Color", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId");

                    b.HasOne("Alpacashow.Models.Participant", "Participant")
                        .WithMany("Animals")
                        .HasForeignKey("ParticipantId");

                    b.HasOne("Alpacashow.Models.Sex", "Sex")
                        .WithMany()
                        .HasForeignKey("SexId");

                    b.HasOne("Alpacashow.Models.ShowEvent", "ShowEvent")
                        .WithMany("Animals")
                        .HasForeignKey("ShowEventId");
                });

            modelBuilder.Entity("Alpacashow.Models.Participant", b =>
                {
                    b.HasOne("Alpacashow.Models.ShowEvent", "ShowEvent")
                        .WithMany("Participants")
                        .HasForeignKey("ShowEventId");
                });
#pragma warning restore 612, 618
        }
    }
}
