// <auto-generated />
using Alpacashow.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Alpacashow.Migrations
{
    [DbContext(typeof(AlpacashowContext))]
    partial class AlpacashowContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Alpacashow.Models.AgeClass", b =>
                {
                    b.Property<int>("AgeClassId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("SortOrder");

                    b.HasKey("AgeClassId");

                    b.ToTable("AgeClasses");
                });

            modelBuilder.Entity("Alpacashow.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("BreedId");

                    b.Property<string>("Chip")
                        .IsRequired();

                    b.Property<int?>("ColorId");

                    b.Property<string>("Dam");

                    b.Property<DateTime>("Dob");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int?>("OwnerId");

                    b.Property<int?>("SexId");

                    b.Property<string>("Sire");

                    b.HasKey("AnimalId");

                    b.HasIndex("BreedId");

                    b.HasIndex("ColorId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("SexId");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("Alpacashow.Models.Breed", b =>
                {
                    b.Property<int>("BreedId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("SortOrder");

                    b.HasKey("BreedId");

                    b.ToTable("Breeds");
                });

            modelBuilder.Entity("Alpacashow.Models.Color", b =>
                {
                    b.Property<int>("ColorId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("SortOrder");

                    b.HasKey("ColorId");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("Alpacashow.Models.Owner", b =>
                {
                    b.Property<int>("OwnerId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FarmName")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("OwnerId");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("Alpacashow.Models.Sex", b =>
                {
                    b.Property<int>("SexId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("SortOrder");

                    b.HasKey("SexId");

                    b.ToTable("Sexes");
                });

            modelBuilder.Entity("Alpacashow.Models.ShowEvent", b =>
                {
                    b.Property<int>("ShowEventId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Archived");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Judge")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int?>("ShowTypeId");

                    b.HasKey("ShowEventId");

                    b.HasIndex("ShowTypeId");

                    b.ToTable("ShowEvents");
                });

            modelBuilder.Entity("Alpacashow.Models.ShowEventAnimal", b =>
                {
                    b.Property<int>("AnimalId");

                    b.Property<int>("ShowEventId");

                    b.HasKey("AnimalId", "ShowEventId");

                    b.HasIndex("ShowEventId");

                    b.ToTable("ShowEventAnimals");
                });

            modelBuilder.Entity("Alpacashow.Models.ShowType", b =>
                {
                    b.Property<int>("ShowTypeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("ShowTypeId");

                    b.ToTable("ShowTypes");
                });

            modelBuilder.Entity("Alpacashow.Models.Animal", b =>
                {
                    b.HasOne("Alpacashow.Models.Breed", "Breed")
                        .WithMany()
                        .HasForeignKey("BreedId");

                    b.HasOne("Alpacashow.Models.Color", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId");

                    b.HasOne("Alpacashow.Models.Owner", "Owner")
                        .WithMany("Animals")
                        .HasForeignKey("OwnerId");

                    b.HasOne("Alpacashow.Models.Sex", "Sex")
                        .WithMany()
                        .HasForeignKey("SexId");
                });

            modelBuilder.Entity("Alpacashow.Models.ShowEvent", b =>
                {
                    b.HasOne("Alpacashow.Models.ShowType", "ShowType")
                        .WithMany()
                        .HasForeignKey("ShowTypeId");
                });

            modelBuilder.Entity("Alpacashow.Models.ShowEventAnimal", b =>
                {
                    b.HasOne("Alpacashow.Models.Animal", "Animal")
                        .WithMany("ShowEventAnimal")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Alpacashow.Models.ShowEvent", "ShowEvent")
                        .WithMany("ShowEventAnimal")
                        .HasForeignKey("ShowEventId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
